spring.application.name=bank.tina
# Neon PostgreSQL Connection Settings
spring.datasource.url=jdbc:oracle:thin:@${ENV_DB_HOST:192.168.143.93:1686:soasysqa}
spring.datasource.username=${ENV_DB_USER:soa_app}
spring.datasource.password=${ENV_DB_PASS:soaapp123}

# Hibernate Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Actuator
management.endpoints.web.exposure.include=health

# DB Pooling
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000